// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJfQs8eSd5u_LN_HMZHvUO7Jhj55a89PI',
    appId: '1:966224291372:web:c8c0e7c4d0abd744279389',
    messagingSenderId: '966224291372',
    projectId: 'kalomon-c4a3b',
    authDomain: 'kalomon-c4a3b.firebaseapp.com',
    storageBucket: 'kalomon-c4a3b.firebasestorage.app',
    measurementId: 'G-SV5ZGD9XP2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxaBpPpsTXzs4pLyif_7fJ1Pspano7z2g',
    appId: '1:966224291372:android:edced699807195e9279389',
    messagingSenderId: '966224291372',
    projectId: 'kalomon-c4a3b',
    storageBucket: 'kalomon-c4a3b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4AYJhTPFv3ASrv6L9gcTnIe03T7MnRXs',
    appId: '1:966224291372:ios:4fcff435a9e8285d279389',
    messagingSenderId: '966224291372',
    projectId: 'kalomon-c4a3b',
    storageBucket: 'kalomon-c4a3b.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4AYJhTPFv3ASrv6L9gcTnIe03T7MnRXs',
    appId: '1:966224291372:ios:4fcff435a9e8285d279389',
    messagingSenderId: '966224291372',
    projectId: 'kalomon-c4a3b',
    storageBucket: 'kalomon-c4a3b.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJfQs8eSd5u_LN_HMZHvUO7Jhj55a89PI',
    appId: '1:966224291372:web:9d04c4acb6033f73279389',
    messagingSenderId: '966224291372',
    projectId: 'kalomon-c4a3b',
    authDomain: 'kalomon-c4a3b.firebaseapp.com',
    storageBucket: 'kalomon-c4a3b.firebasestorage.app',
    measurementId: 'G-TSRX5NMGRW',
  );
}
