import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'dart:convert';

class KitchenPage extends StatefulWidget {
  final String selectedCharacter; const KitchenPage({super.key, required this.selectedCharacter});
  @override State<KitchenPage> createState() => _KitchenPageState();
}

class _KitchenPageState extends State<KitchenPage> {
  final TextEditingController _ingredientController = TextEditingController(); final List<String> _ingredients = []; List<dynamic> _recipes = []; bool _isLoading = false; String _errorMessage = "";
  void _addIngredient() { final text = _ingredientController.text.trim(); if (text.isNotEmpty && !_ingredients.contains(text)) { setState(() { _ingredients.add(text); _ingredientController.clear(); }); } }
  void _removeIngredient(String ingredient) { setState(() => _ingredients.remove(ingredient)); }
  Future<void> fetchRecipes() async { if (_ingredients.isEmpty) { setState(() => _errorMessage = "최소 하나 이상의 식재료를 입력해주세요."); return; } setState(() { _isLoading = true; _errorMessage = ""; _recipes = []; }); try { final response = await http.post(Uri.parse('http://10.0.0.168:8000/api/recipes'), headers: {'Content-Type': 'application/json'}, body: jsonEncode({"ingredients": _ingredients})); if (response.statusCode == 200) { setState(() => _recipes = jsonDecode(utf8.decode(response.bodyBytes))); } else { setState(() => _errorMessage = "서버 오류가 발생했습니다."); } } catch (e) { setState(() => _errorMessage = "네트워크 통신에 실패했습니다."); } finally { setState(() => _isLoading = false); } }
  @override void dispose() { _ingredientController.dispose(); super.dispose(); }
  @override Widget build(BuildContext context) { return Scaffold(backgroundColor: Colors.transparent, appBar: AppBar(title: const Text('칼로레시피', style: TextStyle(fontWeight: FontWeight.bold)), backgroundColor: const Color(0xFF0F172A), elevation: 0), body: Padding(padding: const EdgeInsets.all(16.0), child: Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Row(children: [Expanded(child: TextField(controller: _ingredientController, style: const TextStyle(color: Colors.white), decoration: InputDecoration(hintText: '식재료 입력 (예: 계란, 양파)', hintStyle: const TextStyle(color: Colors.white54), filled: true, fillColor: const Color(0xFF0F172A), border: OutlineInputBorder(borderRadius: BorderRadius.circular(12), borderSide: BorderSide.none), contentPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 14)), onSubmitted: (_) => _addIngredient())), const SizedBox(width: 12), ElevatedButton(onPressed: _addIngredient, style: ElevatedButton.styleFrom(padding: const EdgeInsets.symmetric(vertical: 14, horizontal: 16), backgroundColor: Colors.amber, shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12))), child: const Icon(Icons.add, color: Colors.black))]), const SizedBox(height: 12), Wrap(spacing: 8.0, runSpacing: 4.0, children: _ingredients.map((ingredient) => Chip(label: Text(ingredient, style: const TextStyle(color: Colors.black, fontWeight: FontWeight.bold)), backgroundColor: Colors.amberAccent, deleteIcon: const Icon(Icons.close, size: 18, color: Colors.black54), onDeleted: () => _removeIngredient(ingredient))).toList()), const SizedBox(height: 16), ElevatedButton(onPressed: _isLoading ? null : fetchRecipes, style: ElevatedButton.styleFrom(padding: const EdgeInsets.all(16), backgroundColor: Colors.amber, foregroundColor: Colors.black, disabledBackgroundColor: Colors.amber.withOpacity(0.5)), child: Text(_isLoading ? "생성 중..." : "제안받기", style: const TextStyle(fontSize: 16, fontWeight: FontWeight.bold))), if (_errorMessage.isNotEmpty) ...[const SizedBox(height: 16), Text(_errorMessage, style: const TextStyle(color: Colors.redAccent, fontWeight: FontWeight.bold))], const SizedBox(height: 16), Expanded(child: _isLoading ? const Center(child: CircularProgressIndicator(color: Colors.amberAccent)) : _recipes.isEmpty ? const Center(child: Text("식재료를 입력해주세요.", style: TextStyle(fontSize: 16, color: Colors.white70))) : ListView.builder(itemCount: _recipes.length, itemBuilder: (context, index) { final recipe = _recipes[index]; return Card(color: const Color(0xFF0F172A), margin: const EdgeInsets.only(bottom: 12), child: ExpansionTile(iconColor: Colors.amber, title: Text(recipe['recipe_name'] ?? '요리', style: const TextStyle(fontWeight: FontWeight.bold, color: Colors.white)), children: [Container(padding: const EdgeInsets.all(16.0), child: Text("조리법: ${(recipe['instructions'] as List).join('\n')}", style: const TextStyle(color: Colors.white)))])); }))]))); }
}